background {
    blur = true
}

input-field {
    position = 50%, 60%
    size = 200, 40
    font_size = 18
    inner_color = rgba(0,0,0,0.5)
    font_color = rgba(255,255,255,1.0)
    placeholder_text = "Enter password..."
}

clock {
    position = 50%, 40%
    halign = center
    valign = center
    format = %H:%M
    font_size = 48
}
